[package]
name = "usecases"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { workspace = true }
library-adapter-protocol = { workspace = true }
site-schema = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
sha2 = "0.10"
toml = "0.8"

[dev-dependencies]
mockall = "0.13"
serde_json = { workspace = true }
tempfile = "3"
