use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::ffi::OsString;
use std::time::Duration;

use super::Service;
use crate::command_runner::CommandRequest;

impl Service {
    /// Runs the test command defined in `ce.toml` in the solution directory.
    /// Returns the exit code of the test command (0 = success).
    ///
    /// The command is dispatched through the injected [`CommandRunner`], so a
    /// timeout is enforced (default 600 s; override via `test_timeout_seconds`
    /// in `ce.toml`, positive integers only). A timeout maps to exit code 124
    /// with a `test_command timed out after Ns` line written to stderr.
    ///
    /// [`CommandRunner`]: crate::command_runner::CommandRunner
    pub fn test(&self, contest_id: &str, problem_code: &str, solution_name: &str) -> Result<i32> {
        let solution_dir = self
            .solution_repo
            .solution_dir(contest_id, problem_code, solution_name);

        if !solution_dir.is_dir() {
            anyhow::bail!(
                "solution directory not found: {solution_dir:?}\nRun `ce init` to initialise the contest first."
            );
        }

        let ce_toml_path = solution_dir.join("ce.toml");
        if !ce_toml_path.exists() {
            anyhow::bail!(
                "ce.toml not found in {solution_dir:?}\n\
                 This file is generated by `ce init` from templates/{{lang}}/ce.toml.tera.\n\
                 If the solution directory pre-dates this feature, create ce.toml manually."
            );
        }

        let contents = std::fs::read_to_string(&ce_toml_path)
            .with_context(|| format!("failed to read {ce_toml_path:?}"))?;
        let table: toml::Table = toml::from_str(&contents)
            .with_context(|| format!("failed to parse {ce_toml_path:?}"))?;
        let test_command = table
            .get("test_command")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("`test_command` key not found in {ce_toml_path:?}"))?;

        let timeout_seconds = read_test_timeout_seconds(&table, &ce_toml_path)?;

        #[cfg(not(unix))]
        {
            let _ = (test_command, timeout_seconds);
            anyhow::bail!(
                "test_command execution requires a Unix-like shell (`sh`), which is unsupported on this platform"
            );
        }

        #[cfg(unix)]
        {
            let testcases_dir = self.contest_repo.testcases_dir(contest_id, problem_code);

            let mut environment: BTreeMap<OsString, OsString> = BTreeMap::new();
            // Forward the shell essentials. `PATH` must be present or `sh`
            // cannot resolve external utilities; `HOME` and `TERM` are opt-in.
            for key in ["PATH", "HOME", "TERM"] {
                if let Some(value) = std::env::var_os(key) {
                    environment.insert(OsString::from(key), value);
                }
            }
            environment.insert(
                OsString::from("CE_TESTCASES_DIR"),
                OsString::from(testcases_dir.as_os_str()),
            );

            let request = CommandRequest {
                program: OsString::from("sh"),
                arguments: vec![OsString::from("-c"), OsString::from(test_command)],
                current_dir: solution_dir,
                environment,
                timeout: Duration::from_secs(timeout_seconds),
            };
            let outcome = self.command_runner.run_streaming(&request)?;
            if outcome.timed_out {
                eprintln!("test_command timed out after {timeout_seconds}s");
                // 124 matches the exit code coreutils' `timeout(1)` uses when
                // the wrapped command overruns; downstream tooling can rely on
                // it as a stable timeout signal.
                Ok(124)
            } else {
                // A killed-by-signal child has no exit code. Report 1 so the
                // caller (e.g. `ce submit`'s pre-submit gate) still fails.
                Ok(outcome.exit_code.unwrap_or(1))
            }
        }
    }
}

/// Reads `test_timeout_seconds` from `ce.toml`. Positive integers only; a
/// missing key returns the 600-second default from spec §7.1.
fn read_test_timeout_seconds(table: &toml::Table, ce_toml_path: &std::path::Path) -> Result<u64> {
    match table.get("test_timeout_seconds") {
        None => Ok(600),
        Some(value) => {
            let n = value.as_integer().ok_or_else(|| {
                anyhow::anyhow!(
                    "`test_timeout_seconds` must be a positive integer in {ce_toml_path:?}"
                )
            })?;
            if n <= 0 {
                anyhow::bail!(
                    "`test_timeout_seconds` must be a positive integer in {ce_toml_path:?}, got {n}"
                );
            }
            Ok(n as u64)
        }
    }
}

#[cfg(all(test, unix))]
mod tests {
    use crate::{
        config::Config,
        online_judge::{ContestMeta, CredentialKind, Credentials, OnlineJudge, SingleOnlineJudge},
        repository::{
            contest_repository::ContestRepository, session_repository::SessionRepository,
            solution_repository::SolutionRepository,
        },
        service::Service,
        submission::StarterRegistry,
        test_support::SpawningCommandRunner,
    };
    use anyhow::Result;
    use domain::entity::{Contest, Language, OJKind, Problem, Sample, Session, Solution};
    use std::path::PathBuf;

    // ── Minimal stubs ────────────────────────────────────────────────────────

    struct StubOJ;
    impl OnlineJudge for StubOJ {
        fn name(&self) -> &str {
            "stub"
        }
        fn credential_kind(&self) -> CredentialKind {
            CredentialKind::Cookie
        }
        fn login(&self, _: &Credentials) -> Result<Session> {
            todo!()
        }
        fn whoami(&self, _: &Session) -> Result<String> {
            Ok(String::new())
        }
        fn get_contest_meta(&self, _: &str) -> Result<ContestMeta> {
            todo!()
        }
        fn get_problems_detail(
            &self,
            _: &str,
            _: Option<&Session>,
            _: &[(String, String)],
        ) -> Result<Vec<Problem>> {
            todo!()
        }
    }

    struct StubSession;
    impl SessionRepository for StubSession {
        fn get(&self, _: &OJKind) -> Result<Option<Session>> {
            Ok(None)
        }
        fn save(&self, _: &Session) -> Result<()> {
            Ok(())
        }
        fn delete(&self, _: &OJKind) -> Result<bool> {
            Ok(false)
        }
    }

    struct StubConfig;
    impl Config for StubConfig {
        fn default_language(&self) -> Result<Language> {
            Ok(Language::new("rust"))
        }
        fn default_online_judge(&self) -> OJKind {
            OJKind::AtCoder
        }
        fn submit_file(&self, _: &Language) -> String {
            String::new()
        }
        fn submit_preprocess(&self) -> Option<String> {
            None
        }
        fn lang_id(&self, _: &Language, _: &OJKind) -> Option<String> {
            None
        }
        fn project_root(&self) -> &std::path::Path {
            std::path::Path::new("/tmp/stub-project-root")
        }
    }

    struct StubContestRepo {
        testcases_dir: PathBuf,
    }
    impl ContestRepository for StubContestRepo {
        fn exists(&self, _: &str) -> Result<bool> {
            Ok(true)
        }
        fn exists_unstarted(&self, _: &str) -> Result<bool> {
            Ok(false)
        }
        fn create_unstarted(&self, _: &str) -> Result<()> {
            Ok(())
        }
        fn create(&self, _: &Contest) -> Result<()> {
            Ok(())
        }
        fn get_oj_kind(&self, _: &str) -> Result<OJKind> {
            Ok(OJKind::AtCoder)
        }
        fn get_samples(&self, _: &str, _: &str) -> Result<Vec<Sample>> {
            Ok(vec![])
        }
        fn list_problem_codes(&self, _: &str) -> Result<Vec<String>> {
            Ok(vec![])
        }
        fn testcases_dir(&self, _: &str, _: &str) -> PathBuf {
            self.testcases_dir.clone()
        }
        fn get_problem(&self, _: &str, _: &str) -> Result<domain::entity::Problem> {
            todo!()
        }
    }

    struct StubSolutionRepo {
        solution_dir: PathBuf,
    }
    impl SolutionRepository for StubSolutionRepo {
        fn list(&self, _: &str, _: &str) -> Result<Vec<Solution>> {
            Ok(vec![])
        }
        fn exists(&self, _: &str, _: &str, _: &str) -> Result<bool> {
            Ok(false)
        }
        fn create(&self, _: &Solution, _: &[Sample], _: &str, _: &str) -> Result<()> {
            Ok(())
        }
        fn get_source(&self, _: &Solution, _: &str) -> Result<String> {
            Ok(String::new())
        }
        fn solution_dir(&self, _: &str, _: &str, _: &str) -> PathBuf {
            self.solution_dir.clone()
        }
    }

    fn make_service(solution_dir: PathBuf, testcases_dir: PathBuf) -> Service {
        Service::new(
            Box::new(SingleOnlineJudge::new(Box::new(StubOJ))),
            StarterRegistry::new(),
            Box::new(StubContestRepo { testcases_dir }),
            Box::new(StubSolutionRepo { solution_dir }),
            Box::new(StubSession),
            Box::new(StubConfig),
            Box::new(SpawningCommandRunner),
        )
    }

    // ── Tests ────────────────────────────────────────────────────────────────

    /// A ce.toml with `exit 0` returns exit code 0.
    #[test]
    fn test_returns_zero_on_success() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("ce.toml"), "test_command = \"exit 0\"\n").unwrap();
        let service = make_service(dir.path().to_path_buf(), PathBuf::from("/tmp/testcases"));
        assert_eq!(service.test("abc001", "a", "main").unwrap(), 0);
    }

    /// A ce.toml with `exit 1` returns exit code 1.
    #[test]
    fn test_returns_nonzero_on_failure() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("ce.toml"), "test_command = \"exit 1\"\n").unwrap();
        let service = make_service(dir.path().to_path_buf(), PathBuf::from("/tmp/testcases"));
        assert_eq!(service.test("abc001", "a", "main").unwrap(), 1);
    }

    /// Missing solution directory produces an error mentioning "solution directory not found".
    #[test]
    fn test_errors_when_solution_dir_missing() {
        let service = make_service(
            PathBuf::from("/nonexistent/__ce_test_missing_dir__"),
            PathBuf::from("/tmp/testcases"),
        );
        let err = service.test("abc001", "a", "main").unwrap_err();
        assert!(
            err.to_string().contains("solution directory not found"),
            "unexpected error: {err}"
        );
    }

    /// Existing solution directory with no ce.toml produces an error mentioning "ce.toml not found".
    #[test]
    fn test_errors_when_ce_toml_missing() {
        let dir = tempfile::tempdir().unwrap();
        let service = make_service(dir.path().to_path_buf(), PathBuf::from("/tmp/testcases"));
        let err = service.test("abc001", "a", "main").unwrap_err();
        assert!(
            err.to_string().contains("ce.toml not found"),
            "unexpected error: {err}"
        );
    }

    /// CE_TESTCASES_DIR env var is set to the path returned by contest_repo.testcases_dir().
    #[test]
    fn test_ce_testcases_dir_env_is_set() {
        let solution_dir = tempfile::tempdir().unwrap();
        let testcases_dir = tempfile::tempdir().unwrap();
        let expected = testcases_dir.path().display().to_string();
        // Shell command verifies the env var matches the expected path
        let cmd = format!("test \"$CE_TESTCASES_DIR\" = \"{expected}\"");
        std::fs::write(
            solution_dir.path().join("ce.toml"),
            format!("test_command = \"\"\"\n{cmd}\n\"\"\"\n"),
        )
        .unwrap();
        let service = make_service(
            solution_dir.path().to_path_buf(),
            testcases_dir.path().to_path_buf(),
        );
        assert_eq!(
            service.test("abc001", "a", "main").unwrap(),
            0,
            "CE_TESTCASES_DIR was not set to {expected}"
        );
    }

    /// `test_timeout_seconds = 0` is rejected before invoking the command runner.
    #[test]
    fn test_rejects_zero_timeout() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("ce.toml"),
            "test_command = \"exit 0\"\ntest_timeout_seconds = 0\n",
        )
        .unwrap();
        let service = make_service(dir.path().to_path_buf(), PathBuf::from("/tmp/testcases"));
        let err = service.test("abc001", "a", "main").unwrap_err();
        assert!(
            err.to_string().contains("test_timeout_seconds"),
            "unexpected error: {err}"
        );
    }

    /// A negative `test_timeout_seconds` is rejected before invoking the command runner.
    #[test]
    fn test_rejects_negative_timeout() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("ce.toml"),
            "test_command = \"exit 0\"\ntest_timeout_seconds = -5\n",
        )
        .unwrap();
        let service = make_service(dir.path().to_path_buf(), PathBuf::from("/tmp/testcases"));
        let err = service.test("abc001", "a", "main").unwrap_err();
        assert!(
            err.to_string().contains("test_timeout_seconds"),
            "unexpected error: {err}"
        );
    }
}
