use anyhow::{Context, Result};
use std::process::Command;

use super::Service;

impl Service {
    /// Runs the test command defined in `ce.toml` in the solution directory.
    /// Returns the exit code of the test command (0 = success).
    pub fn test(&self, contest_id: &str, problem_code: &str, solution_name: &str) -> Result<i32> {
        let solution_dir = self
            .solution_repo
            .solution_dir(contest_id, problem_code, solution_name);

        if !solution_dir.is_dir() {
            anyhow::bail!(
                "solution directory not found: {solution_dir:?}\nRun `ce init` to initialise the contest first."
            );
        }

        let ce_toml_path = solution_dir.join("ce.toml");
        if !ce_toml_path.exists() {
            anyhow::bail!(
                "ce.toml not found in {solution_dir:?}\n\
                 This file is generated by `ce init` from templates/{{lang}}/ce.toml.tera.\n\
                 If the solution directory pre-dates this feature, create ce.toml manually."
            );
        }

        let contents = std::fs::read_to_string(&ce_toml_path)
            .with_context(|| format!("failed to read {ce_toml_path:?}"))?;
        let table: toml::Table = toml::from_str(&contents)
            .with_context(|| format!("failed to parse {ce_toml_path:?}"))?;
        let test_command = table
            .get("test_command")
            .and_then(|v| v.as_str())
            .ok_or_else(|| anyhow::anyhow!("`test_command` key not found in {ce_toml_path:?}"))?;

        let testcases_dir = self.contest_repo.testcases_dir(contest_id, problem_code);

        let status = Command::new("/bin/sh")
            .arg("-c")
            .arg(test_command)
            .current_dir(&solution_dir)
            .env("CE_TESTCASES_DIR", &testcases_dir)
            .status()
            .with_context(|| "failed to launch /bin/sh")?;

        Ok(status.code().unwrap_or(1))
    }
}
